# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "identities", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "user_id",     :string
  end

  create_table "projects", :force => true do |t|
    t.column "name",           :string
    t.column "description",    :text
    t.column "user_id",        :string
    t.column "revision",       :string
    t.column "project_number", :string
    t.column "ip_address",     :string
    t.column "port",           :integer
    t.column "connection_id",  :integer
    t.column "branch_number",  :string
  end

end
